

### Emit event
GET http://localhost:5145/event

### Emit event that fails to handle
GET http://localhost:5145/event/error

###
POST http://localhost:5145/dead-letters/
Content-Type: application/json

{
  "Limit": 10
}